CREATE TABLE Tasks
( 
TSK_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
TSK_TASK_ID INTEGER AUTOINCREMENT NOT NULL,
TSK_TASK_NAME VAR  NOT NULL,
TSK_TASK_DESCRIPTION TEXT NOT NULL,
TSK_TASK_DUE_DATE DATETIME NOT NULL
);
COMMIT;