CREATE TABLE WMT_CONTACTS
(
CNT_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
CNT_USR_ID INTEGER NOT NULL,
CNT_NAME VAR NOT NULL,
CNT_SURNAME VAR NOT NULL,
CNT_PHONE_NUMBER VAR NOT NULL UNIQUE,
CNT_DESK_NUMBER VAR NOT NULL,
FOREIGN KEY (CNT_USR_ID) REFERENCES WMT_USERS(USR_ID)
);