CREATE TABLE WMT_TASKS
(
TSK_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
TSK_USR_ID INTEGER NOT NULL,
TSK_NAME VAR  NOT NULL,
TSK_DESCRIPTION TEXT NOT NULL,
TSK_DUE_DATE DATETIME NOT NULL,
FOREIGN KEY (TSK_USR_ID) REFERENCES WMT_USERS(USR_ID)
);
COMMIT;